import type { Metadata } from "next";
import "./globals.css";
import { Inter, Kalam } from "next/font/google";
import Footer from "@/components/layout/footer";
import Header from "@/components/layout/header";
import { Dancing_Script } from "next/font/google";
const dancingScript = Dancing_Script({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-dancing-script",
});
const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const kalam = Kalam({
  subsets: ["latin"],
  weight: ["300", "400", "700"],
  variable: "--font-kalam",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${kalam.variable} ${dancingScript.variable} `}
    >
      <body className="bg-[#FAF6F0]">
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
